---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# Setup external repo for etckeeper
- hosts: all
  become: true
  collections:
    - fruafr.linux
  roles:
    - etckeeper_external_repo_setup

