---
#Generate a ssh key for a user
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
- hosts: all
  become: true
  collections:
    - fruafr.linux
  roles:
    - user_ssh_key_gen
