---
#User present - Create the user if it does not exist
- hosts: all
  become: true
  vars_prompt: 
    - name: "username" 
      prompt: "Enter the username" 
      private: no 
  collections:
    - fruafr.linux
  roles:
    - user_present