# User present in group (added if necessary)
- hosts: all
  become: true
  vars_prompt: 
    - name: "username" 
      prompt: "Enter the username" 
      private: no
    - name: "groupname" 
      prompt: "Enter the group name" 
      private: no
  collections:
    - fruafr.linux
  roles:
    - user_group_present