---
# tasks file for user_sudo_add
# User present in sudo group (added if necessary)

- name: Set username if not specified
  pause:
    prompt: "Enter the username to be present in sudo group" 
  register: username_prompt
  when: username is not defined

- set_fact: 
    username: "{{ username_prompt.user_input }}"
  when: username is not defined

- name: Sudo package must be installed
  become: true
  ansible.builtin.package:
    name: sudo
    state: present
  register: sudopresent

- name: "User {{ username }} in sudo group"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: sudo
    append: true
  when: sudopresent is defined