---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for git_commit_push

#Add files to the commit
- name: "git add for directory {{ git_directory }}"
  shell: git add .
  args:
    chdir: "{{ git_directory }}"

#Get the git status
- name: "git status"
  shell: git status
  args:
    chdir: "{{ git_directory }}"
  register: git_add_status

#Commit
- name: "git commit -a -m \"{{ git_message }}\""
  shell: "git commit -a -m \"{{ git_message }}\""
  args:
    chdir: "{{ git_directory }}"
  ignore_errors: true
  register: git_commit
  when: not git_add_status.stdout is search('nothing to commit')

#Push
- name: git push --force
  shell: git push --force
  args:
    chdir: "{{ git_directory }}"
  register: pushed
  when: (not git_commit is skipped) and git_force

#Push without force if not pushed already
- name: git push
  shell: git push
  args:
    chdir: "{{ git_directory }}"
  when: (not git_commit is skipped) and (pushed is undefined)


