---
# tasks file for user_ssh_key_gen
# Generate a ssh key for the user

- name: "Generate a ssh key for user {{ username }}"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa