---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0

# tasks file for user_ssh_key_gen

# Generate a ssh key for the user

- block:
  - name: Set username if not specified
    pause:
      prompt: "Enter the username" 
    register: username_prompt
  - set_fact: 
      username: "{{ username_prompt.user_input }}"
  when: username is not defined

- name: "Generate a ssh key for user {{ username }}"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa