---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0

# tasks file for user_present

# User must be present (Created if necessary)

- block:
  - name: Set username if not specified
    pause:
      prompt: "Enter the username to be present/added" 
    register: username_prompt
  - set_fact: 
      username: "{{ username_prompt.user_input }}"
  when: username is not defined

# useradd user
- name: "Create the user {{ username }} if it does not exist"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    state: present