---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for packages_etckeeper

# Install etckeeper

# Debian
- block:
  #sudo apt-get update
  - name: APT - Update
    become: true
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 86400 #One day

  #sudo apt-get install etckeeper
  - name: APT - install etckeeper
    become: true
    apt:
      pkg: etckeeper
      state: latest
    register: etckeeper_installed
  when: ansible_os_family == 'Debian'

#RedHat
- block:
  #sudo dnf check-update && sudo dnf install -y [package]
  - name: "DNF check-update and install etckeeper git"
    become: true
    ansible.builtin.dnf:
      name:
        - etckeeper
        - git
      state: latest
      update_cache: true
    when: ansible_distribution_major_version>7  

  #sudo yum install -y [package]
  - name: "yum install -y etckeeper git"
    become: true
    ansible.builtin.yum:
      name: "{{ packages }}"
      state: latest
      update_cache: true
    vars:
      packages:
        - etckeeper
        - git
    when: ansible_distribution_major_version<=7  

  when: ansible_os_family == 'RedHat'

- block:
  #systemctl enable --now etckeeper
  - name: SERVICE - Ensure etckeeper service enabled
    become: true
    service:
      name: etckeeper
      enabled: yes
    register: etckeeper_enabled

  - block:
      #systemctl start etckeeper
    - name: SERVICE - Ensure etckeeper service started
      become: true
      service:
        name: etckeeper
        state: started
      when: ansible_os_family == 'Debian'

    #ls /etc/.git
    - name: Test if /etc/.git is present
      become: true
      stat:
          path: /etc/.git
      register: etc_git

    #mkdir /etc/.git
    - name: ETCKEEPER - Initialize if /etc/.git not present
      become: true
      command:
        cmd: etckeeper init
        creates: /etc/.git
      when: etc_git.stat.exists == false
      register: etc_initialized

    #etckeeper commit "Initial commit"
    - name: ETCKEEPER - Initial commit if initialized
      become: true
      command:
        cmd: etckeeper commit "Initial commit"
      when: etc_initialized is not skipped

    when: etckeeper_enabled

  when: etckeeper_installed is defined
