---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for packages_snapd
# Install snapd
#https://snapcraft.io/docs/installing-snap-on-debian

# Ensures snapd is installed to latest version

# Debian
- block:

  - block:
    #sudo apt-get update && sudo apt-get install -y snapd
    - name: 'APT update and snapd installed'
      become: true
      ansible.builtin.apt:
        pkg:
          - snapd
        state: latest
        update_cache: yes
        cache_valid_time: 86400 #One day
      register: snapd_installed

    #sudo snap install core
    - name: 'install snap core'
      community.general.snap:
        name: core
      when: snapd_installed
 
  when: ansible_os_family == 'Debian'

# Assumes EPEL is installed for RedHat distributions
# RedHat family
- block:
  #sudo dnf check-update && sudo dnf install -y [package]
  - name: "DNF check-update and install snpad"
    become: true
    ansible.builtin.dnf:
      name:
        - snapd
      state: latest
      update_cache: true
    when: ansible_distribution_major_version>7  

  #sudo yum install -y [package]
  - name: "yum install -y etckeeper git"
    become: true
    ansible.builtin.yum:
      name: snapd
      state: latest
      update_cache: true
    when: ansible_distribution_major_version<=7  

  # enable snap
  # sudo systemctl enable --now snapd.socket
  - name: SERVICE - Ensure snapd.socket service enabled
    ansible.builtin.service:
      name: snapd.socket
      enabled: yes

  # create snap classic symlink
  # sudo ln -s /var/lib/snapd/snap /snap
  - name : symlink - /var/lib/snapd/snap /snap
    ansible.builtin.file:
      src: /snap
      dest: /var/lib/snapd/snap
      owner: root
      group: root
      state: link

  when: ansible_os_family == 'RedHat'

