---
# tasks file for group_absent

- block:
  - name: Set groupname if not specified
    pause:
      prompt: "Enter the groupname to be absent/removed"
    register: groupname_prompt  
  - set_fact: 
      groupname: "{{ groupname_prompt.user_input }}"  
  when: groupname is not defined

- name: "group {{ groupname }} absent (removed if needed)"
  become: true
  ansible.builtin.group:
    name: "{{ groupname }}"
    state: absent
