---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for group_present

# Group must be present (created if necessary)

- block:
  - name: Set groupname if not specified
    pause:
      prompt: "Enter the groupname to be present/added"
    register: groupname_prompt  
  - set_fact: 
      groupname: "{{ groupname_prompt.user_input }}"  
  when: groupname is not defined

- name: "group {{ groupname }} present (created if needed)"
  become: true
  ansible.builtin.group:
    name: "{{ groupname }}"
    state: present
