---
# tasks file for hostname_change

- block:
  - name: Set the hostname
    become: true
    ansible.builtin.hostname:
      name: "{{ hostname }}"

  - name: Modify the hostname file /etc/hostname
    become: true
    ansible.builtin.template:
      src: "{{ hostname_template }}"
      dest: /etc/hostname
      owner: root
      group: root
      mode: '0644'

  - name: Update the /etc/hosts file for 127.0.1.1 to 127.0.1.1 fqdn hostname
    become: true
    lineinfile:
      path: "/etc/hosts"
      regexp: "127.0.1.1.*"
      line: "127.0.1.1 {{ fqdn }} {{ hostname }}"
      state: present
      backup: yes





