---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for etckeeper_external_repo_setup

#Setup etckeeper to use an external repository
- name: Set git username if not specified
  pause:
    prompt: "Enter the git username" 
  register: git_username
  when: git_username is not defined

- name: Set git email if not specified
  pause:
    prompt: "Enter the git email" 
  register: git_email_prompt
  when: git_email is not defined

- set_fact: 
    git_email: "{{ git_email_prompt.user_input }}"
  when: git_email is not defined

- name: Set git password if not specified
  pause:
    prompt: "Enter the git password" 
    echo: no
  register: git_password_prompt
  when: git_password is not defined

- set_fact: 
    git_password: "{{ git_password_prompt.user_input }}"
  when: git_password is not defined

- name: Create default remote username if not specified
  set_fact:
    git_remote_user: "{{ ansible_hostname }}"
  when: git_remote_user is not defined

- name: Create default remote repo if not specified
  set_fact:
    git_remote_repo: "{{ ansible_hostname }}-etc.git"
  when: git_remote_repo is not defined

- name: Template the etckeeeper /etc/.git/config file
  become: true
  ansible.builtin.template:
    src: ../templates/config.j2
    dest: /etc/.git/config
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Template the etckeeper /etc/.git/description file
  become: true
  ansible.builtin.template:
    src: ../templates/description.j2
    dest: /etc/.git/description
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Template the etckeeper /root/.gitconfig file
  become: true
  ansible.builtin.template:
    src: ../templates/.gitconfig.j2
    dest: "/root/.gitconfig"
    owner: 'root'
    group: 'root'
    mode: '0644'
  
- name: Template the etckeeper /root/.git-credentials file
  become: true
  ansible.builtin.template:
    src: ../templates/.git-credentials.j2
    dest: "/root/.git-credentials"
    owner: 'root'
    group: 'root'
    mode: '0600'
