---
# tasks file for user_password_set
# Set the user password

#passwd user
- name: "Set the password for user {{ username }}"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"