---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for packages_cockpit

# Install COCKPIT (WebUI)
# https://cockpit-project.org/

# Ubuntu
#Install Cockpit on Ubuntu
#https://www.techrepublic.com/article/install-cockpit-ubuntu-better-server/
#Alternative
#. /etc/os-release
#sudo apt install -t ${VERSION_CODENAME}-backports cockpit
#https://cockpit-project.org/running.html#ubuntu
- block:

  #When not installed
  - block:
    #sudo apt-get update && sudo apt-get install -y cockpit
    - name: 'APT update and cockpit installed'
      become: true
      ansible.builtin.apt:
        pkg:
          - cockpit
        state: latest
        update_cache: yes
        cache_valid_time: 86400 #One day
      register : cockpit_installed

  when: ansible_distribution == "Ubuntu"

# Debian
- block:

  # Enable backports repo with APT and update cache
  - name: 'Enable backports repo with APT and update cache'
    become: true
    apt_repository:
      repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
      state: latest
      filename: backports
      update_cache: yes
    when: (ansible_distribution_release == 'wheezy') or
        (ansible_distribution_release == 'jessie') or
        (ansible_distribution_release == 'stretch') or
        (ansible_distribution_release == 'buster') or
        (ansible_distribution_release == 'bullseye')


   # install package from backports
  - name: 'APT update and cockpit installed'
    become: true
    ansible.builtin.apt:
      pkg:
        - cockpit
      state: latest
      update_cache: yes
      cache_valid_time: 86400 #One day
    register : cockpit_installed

  when: ansible_os_family == "Debian" and ansible_distribution != "Ubuntu"

# RedHat systems
- block:

    # RHEL version 7 (CentOS 7)
    - name: 'RHEL 7 - install cockpit with yum'
      become: true
      ansible.builtin.yum:
        name: cockpit
        state: latest
        update_cache: yes
      when: ansible_distribution_major_version==7
      register : cockpit_installed

    # RHEL > 7 (Fedora, Almalinux, Rockylinux)
    - name: 'RHEL 7 - install cockpit with dnf'
      become: true
      ansible.builtin.dnf:
        name: cockpit
        state: latest
        update_cache: yes
      when: ansible_distribution_major_version>7 
      register : cockpit_installed

  when: ansible_os_family == "RedHat"

## COMMON
- block:
  #sudo systemctl enable --now cockpit
  - name: SERVICE - Ensure cockpit service enabled
    service:
      name: cockpit
      enabled: yes
  #pause
  - name: pause 15 seconds
    pause:
      seconds: 15
  #sudo systemctl start cockpit
  - name: SERVICE - Ensure cockpit service started
    service:
      name: cockpit
      state: started
  when: cockpit_installed is succeeded
