---
# tasks file for packages_snapd_test

#Test snapd with hello-world

- name: 'test with hello world - should be present'
  community.general.snap:
    name: hello-world
    state: present

- shell: hello-world
  register: msg

- name: 'test output'
  debug: var=msg.stdout_lines

- name: 'test with hello world - should be absent'
  community.general.snap:
    name: hello-world
    state: absent